dir: /root/ad_ecg/anomaly_detection_ecg/ecg_data
#dir: ecg_data
model_name: if
mlflow_model_name: isolation-forest-model

mlflow_url: https://dagshub.com/eugenia.anello/anomaly_detection_ecg_part2.mlflow 
MLFLOW_TRACKING_USERNAME: eugenia.anello
MLFLOW_TRACKING_PASSWORD: bd3592a38029adedb7da200ee3281176919c5d18  
DAGSHUB_REPO_NAME: anomaly_detection_ecg_part2

aws_access_key_id: secrets.AWS_ACCESS_KEY_ID
aws_secret_access_key: secrets.AWS_SECRET_ACCESS_KEY
region_name: secrets.REGION_NAME

## hyperparameters of ae
n_epochs: 30
batch_size: 32
optimizer: adam
type_loss: mae
patience: 5

## hyperparameters of isolation forest
contamination: 0.004