name: Create envfile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: install packages
      run: pip install -r requirements.txt
    - name: Configure AWS credentials from Test account
      env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ${{ secrets.REGION_NAME }} 
      run: streamlit run src/ecg_app.py

