- name: Run tests
  env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REGION_NAME: ${{ secrets.REGION_NAME }}
  run: |
     nbdev_test_nbs
